### ISSUE TITLE
How do i figure out the endpoint url if I've set up an ELK server?

### ISSUE THREAD

**Issue by BrianGilbert** [Gizra/logs_http#8]
I used the setup instructions at https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-elk-stack-on-ubuntu-14-04

But am not sure how to figure out what the endpoint url should be, and can't find any documentation in the module that indicates how you might find it.

Are you please able to assist?

Thanks
Brian

**Comment by amitaibu** [comment]
Sorry, I'm working with Loggly, and I don't remember how we got the URL [here](http://www.gizra.com/content/logs-easy-way/)

**Comment by amitaibu** [comment]
But I'd love to know, once you figure it out :)

**Comment by Sturgelose** [comment]
@amitaibu 

I leave here for other people how to use this module with logstash :)
- Enable `logstash-hhtp-input` plugin, so we can listen http input from the module. (Could be good if the module had TCP or UDP support alternative, as right now it can only be HTTP(s) ). You can do so using gosu and the next command
  `gosu logstash bin/logstash-plugin install logstash-input-http`
-  Setup listening port and use the plugin in Logstash input function. Example:

```
# Listen to port 5000 for incoming http calls
input {
  http {
    port => 5000
    codec => json
  }
}
```

The JSON codec will parse everything for you. If you save to elasticsearch you will get a record such as (so mostly with everything parsed for you):

``` json
{
      "_index" : "logstash-2016.10.24",
      "_type" : "Notice",
      "_id" : "AVf2wUuXbCXQWhivUROJ",
      "_score" : 1.0,
      "_source" : {
        "timestamp" : 1477313643,
        "type" : "Notice",
        "ip" : "10.42.143.163",
        "request_uri" : "http://kratos.esn.org/user/login",
        "referer" : "http://kratos.esn.org/user/login",
        "uid" : "1",
        "message" : "Session opened for Admin.",
        "severity" : 5,
        "uuid" : "drupal-test",
        "@version" : "1",
        "@timestamp" : "2016-10-24T12:54:04.301Z",
        "host" : "10.42.209.17",
        "headers" : {
          "request_method" : "POST",
          "request_path" : "/",
          "request_uri" : "/",
          "http_version" : "HTTP/1.1",
          "http_user_agent" : "Drupal/8.2.1 (+https://www.drupal.org/) GuzzleHttp/6.2.1 curl/7.38.0 PHP/7.0.12",
          "content_type" : "application/json",
          "http_host" : "elk.elk.rancher.internal:5000",
          "content_length" : "245"
        }
      }
    }
```
- Set the URL in the plugin:
  http://logstashserver:port
- Profit!

Maybe we could add this to the documentation :)

Also, as a comment I think that the `severity` and `type` attributes are redundant as they expose the same. Couldn't be an option to expose instead of `type` the proper Type, such as `cron`, `acces denied` or `php`?? I think I can do a pull request with a patch for this :)

Anyway, thanks a lot for the module, it helps a lot!

**Comment by amitaibu** [comment]
Thanks. @ordavidil are you getting these notifications?

**Comment by ordavidil** [comment]
@amitaibu 
yeah,  I'll try to replicate this on both branches to make sure and then update the docs.

**Comment by Sturgelose** [comment]
@ordavidil @amitaibu, It's been some time since I pushed the changes. Any update on this?

**Comment by ordavidil** [comment]
yes, sorry, I couldn't find the time to handle this back then, although it's pretty much ready for release ...

I'll take care of that in the next few days ...
